### PR TITLE
Added stuff from Ronny

### PR DESCRIPTION
**Pull request by indigo423**

### CODE REVIEW

**Comment by mvrueden** [comment]
Please use a meaningful commit message. 
`Added stuff from Ronny` doesn't say much.
It sounds like `some change`, `a change`, `some removals`, etc.

**Comment by mvrueden** [comment]
Seems, that I was too late...

**Comment by indigo423** [comment]
yes its every week the same, jeff introduced this repo for stuff which should be mentioned in the next twio. It's not software.

**Comment by mvrueden** [comment]
Yeah, I saw that it is twio-fodder instead of opennms, but afterwards. Sorry.

**Pull request merged**
